name: Deploy Storybook to Pages

on:
  push:
    branches:
      - storybook
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./example

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Wait for npm publish
        run: sleep 30

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Replace local links with actual versions
        run: |
          sed -i 's#"bear-react-carousel": "link:.."#"bear-react-carousel": "latest"#' package.json
          sed -i 's#"react": "link:../node_modules/react"#"react": "^18.0.0"#' package.json
          sed -i 's#"react-dom": "link:../node_modules/react-dom"#"react-dom": "^18.0.0"#' package.json

      - name: Install dependencies
        run: yarn install

      - name: Build Storybook
        run: yarn build-storybook

      - name: Install Wrangler
        run: yarn global add wrangler

      - name: Deploy to Cloudflare Pages
        run: wrangler pages deploy ./storybook-static --project-name=bear-react-carousel-storybook --branch main
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
